version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11 # Asegúrate de que esta versión coincida con la de tu Lambda
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      # Empaqueta tu aplicación SAM
      # --s3-bucket: Bucket donde se subirán los artefactos del código de Lambda (ZIP files)
      # --output-template-file: Nombre del archivo de plantilla de SAM después de empaquetar
      - sam package --template-file template.yaml --s3-bucket tfm-ucm-artefactos  --output-template-file packaged.yaml
artifacts:
  files:
    # Este archivo es el artefacto principal que CodePipeline usará para el despliegue
    - packaged.yaml