Transform: AWS::Serverless-2016-10-31
Resources:
  StateMachine85ffde05:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: A description of my state machine
        StartAt: Map
        States:
          Map:
            Type: Map
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: Obtener mediciones para cada sensor
              States:
                Obtener mediciones para cada sensor:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  Output: '{% $states.result.Payload %}'
                  Arguments:
                    FunctionName: ${lambdainvoke_FunctionName_e642879b}
                    Payload: '{% $states.input %}'
                  Retry:
                    - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        - Lambda.TooManyRequestsException
                      IntervalSeconds: 1
                      MaxAttempts: 3
                      BackoffRate: 2
                      JitterStrategy: FULL
                  End: true
            End: true
            MaxConcurrency: 1
        QueryLanguage: JSONata
      DefinitionSubstitutions:
        lambdainvoke_FunctionName_e642879b: >-
          arn:aws:lambda:us-east-1:533267130424:function:get_open_aq_data:$LATEST
      Name: StateMachine85ffde05
      Type: STANDARD
      Role:
        Fn::GetAtt:
          - Roleb212254e
          - Arn
      Logging:
        Level: 'ALL'
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn:
                Fn::GetAtt:
                  - LogGroup8572f959
                  - Arn
  Roleb212254e:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StepFunctions_IAM_ROLE_OpenAQStepFunction511b5e70
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - lambda.amazonaws.com
                - states.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
  Policy0730d8c3:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: AWSLambdaBasicExecutionRole9e1bcc18
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: logs:CreateLogGroup
            Resource: arn:aws:logs:us-east-1:533267130424:*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - >-
                arn:aws:logs:us-east-1:533267130424:log-group:/aws/lambda/read_csv_from_s3:*
  Policy34921e2d:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: AWSLambdaS3ExecutionRole63633d68
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:ListAllMyBuckets
            Resource: arn:aws:s3:::*
  Policy1abbb81d:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: AWSGlueConsoleRoleInlinePolicyc06ff763
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - arn:aws:s3:::tfm-ucm/*
              - arn:aws:s3:::tfm-ucm
  Policye3ca0a40:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: GetSecretValue44cb0be9
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - '*'
  Policy0c605399:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: glue_BatchCreatePartition31c542bd
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - glue:BatchCreatePartition
            Resource:
              - arn:aws:glue:us-east-1:533267130424:catalog
              - arn:aws:glue:us-east-1:533267130424:database/tfm-ucm
              - arn:aws:glue:us-east-1:533267130424:table/tfm-ucm/measurments
              - arn:aws:glue:us-east-1:533267130424:table/tfm-ucm/locations
              - arn:aws:glue:us-east-1:533267130424:table/tfm-ucm/parameters
  Policyfb79d06d:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: glue_GetTable92f38e71
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - glue:GetTable
            Resource:
              - arn:aws:glue:us-east-1:533267130424:catalog
              - arn:aws:glue:us-east-1:533267130424:database/tfm-ucm
              - arn:aws:glue:us-east-1:533267130424:table/tfm-ucm/measurments
              - arn:aws:glue:us-east-1:533267130424:table/tfm-ucm/parameters
              - arn:aws:glue:us-east-1:533267130424:table/tfm-ucm/locations
  Policy0871f8fa:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: lambda_InvokeFunction0a95040c
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - >-
                arn:aws:lambda:us-east-1:533267130424:function:get_openaq_sensors
              - arn:aws:lambda:us-east-1:533267130424:function:get_open_aq_data
              - >-
                arn:aws:lambda:us-east-1:533267130424:function:get_open_aq_data:$LATEST
              - arn:aws:lambda:us-east-1:533267130424:function:getHealthData
              - arn:aws:lambda:us-east-1:533267130424:function:get_ree_data
              - >-
                arn:aws:lambda:us-east-1:533267130424:function:DividirSensoresEnLotes
  Policyc19de02f:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: logsf0f21d37
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogDelivery
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:ListLogDeliveries
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
              - logs:DescribeLogGroups
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
  Policy8f993bd9:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: read86b58f1f
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
            Resource: arn:aws:s3:::tfm-ucm/*
  Policy1bceb13e:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: StepFunction0d6ec2bc
      RoleName:
        Ref: Roleb212254e
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - states:RedriveExecution
              - states:DescribeExecution
              - states:StartExecution
              - states:StopExecution
              - events:PutTargets
              - events:PutRule
              - events:DescribeRule
            Resource:
              - arn:aws:states:*:533267130424:express:*:*:*
              - arn:aws:states:*:533267130424:stateMachine:*
              - arn:aws:states:*:533267130424:execution:*:*
              - >-
                arn:aws:states:us-east-1:533267130424:stateMachine:OpenAQStepFunction
              - >-
                arn:aws:events:us-east-1:533267130424:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
              - arn:aws:lambda:us-east-1:533267130424:function:getHealthData
              - arn:aws:lambda:us-east-1:533267130424:function:get_ree_data
              - >-
                arn:aws:lambda:us-east-1:533267130424:function:DividirSensoresEnLotes
  LogGroup8572f959:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/vendedlogs/states/StateMachine85ffde05-Logs
